# troubleshoot-networking.yaml
apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
  labels:
    app: network-debug
spec:
  containers:
  - name: network-tools
    image: nicolaka/netshoot:latest
    command: ['sleep', '3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"