# advanced-clusterip.yaml
# Multi-port service with named ports
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-port-app
  labels:
    app: multi-port
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-port
  template:
    metadata:
      labels:
        app: multi-port
    spec:
      containers:
      - name: web-app
        image: nginx:1.21
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: metrics
          containerPort: 9090
        env:
        - name: SERVICE_TYPE
          value: "multi-port"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: http  # Using named port
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
---
# Multi-port ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  labels:
    app: multi-port
  annotations:
    service.kubernetes.io/topology-aware-routing: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: multi-port
  ports:
  - name: http
    port: 80
    targetPort: http    # Reference named port
    protocol: TCP
  - name: https
    port: 443
    targetPort: https   # Reference named port
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics # Reference named port
    protocol: TCP
  # Session affinity for sticky sessions
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour session stickiness