# clusterip-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: "1.0"
    spec:
      containers:
      - name: api
        image: nginx:1.21
        ports:
        - name: http
          containerPort: 80
        env:
        - name: SERVER_TYPE
          value: "backend"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
# ClusterIP Service (default type)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    service-type: clusterip
spec:
  type: ClusterIP  # Default, can be omitted
  selector:
    app: backend    # Matches pods with this label
  ports:
  - name: http      # Named port for clarity
    port: 80        # Service port (what clients connect to)
    targetPort: 80  # Pod port (where traffic is forwarded)
    protocol: TCP
  # Optional: specify cluster IP (usually auto-assigned)
  # clusterIP: 10.96.1.100
---
# Test client deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: busybox:1.35
        command: ['sleep', '3600']
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"