# loadbalancer-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web-app
  labels:
    app: public-web
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: public-web
  template:
    metadata:
      labels:
        app: public-web
        tier: frontend
    spec:
      containers:
      - name: web-server
        image: nginx:1.21
        ports:
        - name: http
          containerPort: 80
        env:
        - name: SERVICE_TYPE
          value: "LoadBalancer"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
        # Create custom content
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "<!DOCTYPE html>
                <html>
                <head><title>LoadBalancer Demo</title></head>
                <body>
                  <h1>LoadBalancer Service Demo</h1>
                  <p><strong>Pod:</strong> $(hostname)</p>
                  <p><strong>Service Type:</strong> LoadBalancer</p>
                  <p><strong>Timestamp:</strong> $(date)</p>
                  <p>This pod is behind a cloud load balancer!</p>
                </body>
                </html>" > /usr/share/nginx/html/index.html
---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: public-loadbalancer
  labels:
    app: public-web
    service-type: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: public-web
  ports:
  - name: http
    port: 8080         # External load balancer port
    targetPort: http # Pod port
    protocol: TCP
  # Optional: Specify load balancer source ranges
  loadBalancerSourceRanges:
  - "0.0.0.0/0"     # Allow from anywhere (default)
  # - "10.0.0.0/8"   # Restrict to specific CIDR blocks
  # - "192.168.0.0/16"
  
  # Traffic distribution
  externalTrafficPolicy: Cluster  # Cluster or Local
  sessionAffinity: None           # None or ClientIP