# nodeport-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - name: web
          containerPort: 80
        env:
        - name: TIER
          value: "frontend"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 10
        # Custom content showing pod info
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "<h1>Frontend Pod: $(hostname)</h1>" > /usr/share/nginx/html/index.html
                echo "<p>Node: $NODE_NAME</p>" >> /usr/share/nginx/html/index.html
                echo "<p>Pod IP: $POD_IP</p>" >> /usr/share/nginx/html/index.html
                echo "<p>Timestamp: $(date)</p>" >> /usr/share/nginx/html/index.html
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  labels:
    app: frontend
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80          # ClusterIP port
    targetPort: web   # Pod port
    nodePort: 30080   # External port on nodes (30000-32767)
    protocol: TCP
  # Optional: External traffic policy
  externalTrafficPolicy: Local  # Preserve source IP and reduce hops