apiVersion: v1
kind: Pod
metadata:
  name: backend-prod
  labels:
    app: backend
    environment: production
    tier: api
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ['sleep', '3600']
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"