apiVersion: v1
kind: Pod
metadata:
  name: exercise-pod
  labels:
    app: exercise
    version: v1
spec:
  containers:
  - name: web
    image: nginx:1.21
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      value: "learning"
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"