# advanced-rollout-strategies.yaml
# Blue-Green style deployment (manual process)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: color-demo
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-demo
      color: blue
  template:
    metadata:
      labels:
        app: color-demo
        color: blue
        version: "blue"
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "blue"
        - name: VERSION
          value: "1.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: color-service
  labels:
    app: color-demo
spec:
  selector:
    app: color-demo
    color: blue  # Initially pointing to blue
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# Green deployment (new version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: color-demo
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-demo
      color: green
  template:
    metadata:
      labels:
        app: color-demo
        color: green
        version: "green"
    spec:
      containers:
      - name: app
        image: nginx:1.22  # New version
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "green"
        - name: VERSION
          value: "2.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"