# basic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
    tier: frontend
spec:
  # Replica management
  replicas: 3
  
  # Selector for pods managed by this deployment
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  
  # Pod template (similar to Chapter 4 pod specs)
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
        version: "1.0"
    spec:
      containers:
      - name: web-server
        image: nginx:1.21
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10