# deployment-rs-relationship.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: relationship-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relationship-demo
  template:
    metadata:
      labels:
        app: relationship-demo
        version: "1.0"
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "1.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"